name: cd

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install
      - run: pnpm build
      - run: pnpm publish --provenance --access --no-git-checks
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_MOCHI_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_MOCHI_TOKEN}}