name: cd

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'dev'

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish --tag latest --provenance --access public --publish-branch dev
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NPM_MOCHI_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_MOCHI_TOKEN}}