name: ci

on:
  workflow_call:
  push:
    branches:
      - '*'
  pull_request:
    types: [review_requested]

env: 
  HUSKY: 0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm test