name: build-and-deploy
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Publish
        run: cargo publish --token ${{ secrets.CRATES_MOCHI_TOKEN }}