name: lint

on: 
  push:
    branches:
      - '*'
  pull_request:
    types: [review_requested]

jobs:
  lint:
    runs-on: ubuntu-latest
    env: 
      HUSKY: 0

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: corepack enable
      - run: corepack prepare pnpm@latest --activate
      - run: pnpm install

      - run: pnpm lint -f github-annotations 
        continue-on-error: true