name: build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install latest rust nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - run: cargo test